### ISSUE TITLE
Python 2 Support?!! old dependencies

### ISSUE THREAD

**Issue by forexstudies** [codescandy/Dash-UI#3]
Just executed the npm install and it seems this project has a dependency that only supports Python2

here is the output note thaat I have python3 on my machine

```
npm ERR! code 1
npm ERR! path C:\my-dev\path\dash-ui\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\my-dev\path\dash-ui\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\mydev\\path\\dash-ui\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.6.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\my-dev\path\dash-ui\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\my-dev\path\dash-ui\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\my-dev\path\dash-ui\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\my-dev\path\dash-ui\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\my-dev\path\dash-ui\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\my-dev\path\dash-ui\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\my-dev\path\dash-ui\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\mydev\\path\\dash-ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\my-dev\path\dash-ui\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.6.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Local\npm-cache\_logs\2021-08-29T03_14_06_868Z-debug.log

```

**Comment by forexstudies** [comment]
Even after installing python2 this failed

**Comment by anitaparmar26** [comment]
Yes, You can try to update dependencies and have to update gulp-sass with sass ( npm install sass gulp-sass --save-dev )

 autoprefixer   ^10.2.6  →  ^10.3.3
 browser-sync  ^2.26.14  →  ^2.27.5
 cssnano         ^5.0.6  →   ^5.0.8
 gulp-postcss    ^9.0.0  →   ^9.0.1
 gulp-sass       ^4.1.0  →   ^5.0.0
 node-sass       ^6.0.0  →   ^6.0.1
 postcss         ^8.3.5  →   ^8.3.6
 apexcharts     ^3.26.2  →  ^3.28.1
 bootstrap       ^5.0.1  →   ^5.1.0
 prismjs        ^1.23.0  →  ^1.24.1

I fixed the bug and updated all dependencies in the package.json file.
