### ISSUE TITLE
Please update the README to describe how to fix initial install problems/fix installations issues

### ISSUE THREAD

**Issue by plastikfan** [codescandy/Dash-UI#4]
I have just attempted to get your template up and running, however, the intall process documented just resulted in a lot of errors and a failed attempt to install.

Please can you document your assumptions, eg what version of npm, version of gulp. This [article](https://www.sitepoint.com/how-to-migrate-to-gulp-4/) shows how to uprgrade to Gulp V4, I'm not sure if  have to do this or not, but as it stands, the template does not currently work.

PS: I am using WSL2 on windows running ubuntu 20.04

here is my gulp install result:

```
 ✘ plastikfan@Janus  ~/dev/github/front/Dash-UI λ   main ±  npm install gulp-cli -g
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/home/plastikfan/.nvm/versions/node/v10.23.0/bin/gulp -> /home/plastikfan/.nvm/versions/node/v10.23.0/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@2.3.0
added 252 packages from 165 contributors in 9.245s
```

and here is the result of running the gulp command:

```
 plastikfan@Janus  ~/dev/github/front/Dash-UI λ   main ±  gulp
TypeError: series is not a function
    at Object.<anonymous> (/home/plastikfan/dev/github/front/Dash-UI/gulpfile.js:181:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at requireOrImport (/home/plastikfan/.nvm/versions/node/v10.23.0/lib/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/home/plastikfan/.nvm/versions/node/v10.23.0/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:30:3)
 ✘ plastikfan@Janus  ~/dev/github/front/Dash-UI λ   main ± 
```

As you can see, I'm running node version: v10.23.0, but this also failed on node version: v14.15.0. I switched to trying v10 as a result of finding this on stackoverflow: [gulp Package task -ReferenceError: primordials is not defined](https://stackoverflow.com/questions/58856370/gulp-package-task-referenceerror-primordials-is-not-defined)

**Comment by plastikfan** [comment]
This error was caused by the fact gulp 3.9.1 kept getting installed instead of the minimum of gulp 4. Had to also remove node_modules before proceeding with additional attempts otherwise it remains in a bad state. Perhaps the install guidelines should suggest checking that gulp 4 is installed not version 3.x, because that doesnt work.
